---

- name: "6.2.2.1 | PATCH | Ensure audit log storage size is configured"
  when: deb12cis_rule_6_2_2_1
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.2.1
    - NIST800-53R5_AU-8
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "^max_log_file( |=)"
    line: "max_log_file = {{ deb12cis_auditd_max_log_file_size }}"
  notify: Restart auditd

- name: "6.2.2.2 | PATCH | Ensure audit logs are not automatically deleted"
  when: deb12cis_rule_6_2_2_2
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.2.2
    - NIST800-53R5_AU-8
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "^max_log_file_action"
    line: "max_log_file_action = {{ deb12cis_auditd_max_log_file_action }}"
  notify: Restart auditd

- name: "6.2.2.3 | PATCH | Ensure system is disabled when audit logs are full"
  when: deb12cis_rule_6_2_2_3
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.2.3
    - NIST800-53R5_AU-2
    - NIST800-53R5_AU-8
    - NIST800-53R5_AU-12
    - NIST800-53R5_SI-5
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify: Restart auditd
  loop:
    - { regexp: '^disk_full_action', line: 'disk_full_action = {{ deb12cis_auditd_disk_full_action }}' }
    - { regexp: '^disk_error_action', line: 'disk_error_action = {{ deb12cis_auditd_disk_error_action }}' }

- name: "6.2.2.4 | PATCH | Ensure system warns when audit logs are low on space"
  when: deb12cis_rule_6_2_2_4
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.2.4
    - NIST800-53R5_AU-2
    - NIST800-53R5_AU-8
    - NIST800-53R5_AU-12
    - NIST800-53R5_SI-5
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify: Restart auditd
  loop:
    - { regexp: '^space_left_action', line: 'space_left_action = {{ deb12cis_auditd_space_left_action }}' }
    - { regexp: '^admin_space_left_action', line: 'admin_space_left_action = {{ deb12cis_auditd_admin_space_left_action }}' }

- name: "PATCH | Configure other keys for auditd.conf"
  when:
    - deb12cis_auditd_extra_conf.keys() | length > 0
    - deb12cis_auditd_extra_conf_usage
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - NIST800-53R5_AU-2
    - NIST800-53R5_AU-8
    - NIST800-53R5_AU-12
    - NIST800-53R5_SI-5
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "^{{ item }}( |=)"
    line: "{{ item }} = {{ deb12cis_auditd_extra_conf[item] }}"
  loop: "{{ deb12cis_auditd_extra_conf.keys() }}"
  notify: Restart auditd
